### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by riscie** [lasantosr/intelli-shell#1]
Hi!
I found your project via your comment in the pet repo.
After looking trough the repo briefly, my assumption is, that on windows, intelli-shell will only work within a wsl shell, correct?
Is a powershell integration even possible?

**Comment by lasantosr** [comment]
Hello!

Using an WSL instance is fully functional, as it's running under a Linux distro.

About PowerShell, I've minimally tested it on PowerShell and it's functional (using the cli), but I don't think it's possible to integrate it with shortcuts using current line. If someone have some insights on this let me know.

There's no installation script, but you can download the windows version and execute it (or use `cargo install` or compile it yourself).
Maybe `.exe` extension is needed, I'll test it again and update readme accordingly.

**Comment by riscie** [comment]
Nice! I‘ll check it out.

**Comment by lasantosr** [comment]
Terminal support is given by crossterm, which has an open issue for that: https://github.com/crossterm-rs/crossterm/issues/580

So, for the moment, there is no support for Git Bash or similar on Windows 😕
