### ISSUE TITLE
Issues on powershell

### ISSUE THREAD

**Issue by David-Alfred** [lasantosr/intelli-shell#2]
Hello, Thanks very much for such a wonderful tool to improve my efficiency. But I am facing a trouble, and I am not sure whether that's because I have made some mistakes during my installing this tools.

After I installed it, and type the command below:

`intelli-shell -h`

I could get nothing from the terminal, and after I typed the command:

`intelli-shell fetch`

there was still no reaction from the terminal.

My PC Imformation:

- powershell 7.3.4
- windows 11
- have followed the steps to install intelli-shell

**Comment by lasantosr** [comment]
On windows, you need to include the extension: `intelli-shell.exe fetch`

If it doesn't work, try to clean anything related to intelli-shell from `$Profile` and user's `$PATH` and try to install again

**Comment by David-Alfred** [comment]
The problem solved! Thanks!
